stages:
  - mon_test

job:mon_test:
  stage: mon_test
  image: python:3.6
  script:
    - apt-get update -qy
    - sh install.sh
    - python3 ./resolution_coreferences_pronominales/__main__.py
    - for f in resolution_coreferences_pronominales/tests/*.py; do if [ $f != resolution_coreferences_pronominales/tests/test-duree_execution.py and $f != resolution_coreferences_pronominales/tests/test-spacy.py]; then python3 "$f"; fi; done
    - python3 resolution_coreferences_pronominales/tests-regression/test-duree_execution.py 1 1
    - sh uninstall.sh



